include:
  - path: compose/qdrant.yaml
    project_directory: .
  - path: compose/app.yaml
    project_directory: .
  - path: compose/ollama.yaml
    project_directory: .
  #- path: compose/openwebui.yaml
  #  project_directory: .
  - path: compose/lobechat.yaml
    project_directory: .
  - path: compose/opencode.yaml
    project_directory: .
